# Outlook Mail connector test configuration
name: "Outlook Mail Connector Test"
description: "End-to-end test of Outlook Mail connector sync functionality with incremental deletion testing"

connector:
  name: "outlook_mail_test"
  type: "outlook_mail"
  auth_mode: composio
  composio_config:
    account_id: ca_PGX8SpTpUyXI
    auth_config_id: ac_75wtnvwZDUuq
  config_fields:
    openai_model: "gpt-4.1-mini"

    # Timing: Allow Outlook API to index newly created emails
    # Outlook needs time to propagate new messages through its systems before they appear in listings
    post_create_sleep_seconds: 20

    # Folder Filters: Use permissive filtering for test environment
    # Include both inbox and sentitems to catch self-sent test emails
    included_folders: ["inbox", "sentitems"]
    excluded_folders: ["junkemail", "deleteditems"]

    # Note on Continuous Sync Behavior:
    # Outlook Mail supports continuous/incremental sync via deltaToken tracking.
    # - First sync: Full sync of all matching messages, captures final deltaToken
    # - Subsequent syncs: Only changes since last deltaToken (additions/deletions)
    # This means test emails MUST be created and properly labeled BEFORE the first sync
    # completes, otherwise they won't appear in subsequent incremental syncs.

test_flow:
  steps:
    - cleanup
    - create
    - force_full_sync
    - verify
    - partial_delete
    - force_full_sync
    - verify_partial_deletion
    - verify_remaining_entities
    - force_full_sync
    - verify_remaining_entities
    - complete_delete
    - force_full_sync
    - verify_complete_deletion
    - cleanup

# Entity configuration
entity_count: 3  # Number of entities to create for testing

deletion:
  # Phase 1: Partial deletion
  partial_delete_count: 1  # Number of entities to delete during partial deletion

  # Verification settings
  verify_partial_deletion: true
  verify_remaining_entities: true
  verify_complete_deletion: true

collection:
  name_template: "monke-{connector_type}-test-{timestamp}"
  description: "Test collection for {connector_type} connector"

verification:
  score_threshold: 0.1
  max_retries: 3
  retry_delay_seconds: 5

# Test-specific configuration
# test_config:
#   Any source-specific configuration can go here
